/*
    File2Array.c
    Copyright (c) 2023,2024. Gerardo Ospina

    This program generates a C array initialized with the contents of a binary
    file

    Permission is hereby granted, free of charge, to any person obtaining a
    copy of this software and associated documentation files (the "Software"),
    to deal in the Software without restriction, including without limitation
    the rights to use, copy, modify, merge, publish, distribute, sublicense,
    and/or sell copies of the Software, and to permit persons to whom the
    Software is furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included in
    all copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
    GERARDO OSPINA BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
    IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
    CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

    Except as contained in this notice, the name of Gerardo Ospina shall not be
    used in advertising or otherwise to promote the sale, use or other dealings
    in this Software without prior written authorization from Gerardo Ospina.
*/

#include <stdlib.h>
#include <stdio.h>

#include "File2Array.h"

static void read_copy(FILE *, FILE *, char *, char *);
static void print_header(FILE *, char *, char *);
static void copy(Tbuffer, int, FILE *, int *);
static void print_footer(FILE *);

int main(int argc, char *argv[])
{
    if (argc != 4)
    {
        printf("usage File2Array <binary file> <header file> <C array name>\n");
    }
    else
    {
        FILE *in = fopen(argv[1], "r");

        if (in == NULL)
        {
            printf("Unable to open binary file: %s\n", argv[1]);
        }
        else
        {
            FILE *out = fopen(argv[2], "w");

            if (out == NULL)
            {
                printf("Unable to create header file: %s\n", argv[2]);
            }
            else
            {
                read_copy(in, out, argv[2], argv[3]);
                fclose(out);
            }
            fclose(in);
        }
    }
    return EXIT_SUCCESS;
}

static void read_copy(FILE *in, FILE *out, char *filename, char *dsname)
{
    int pos = 0;
    Tbuffer buffer;
    int n;

    print_header(out, filename, dsname);
    n = fread(buffer, sizeof(unsigned char), BUFFER_LENGTH, in);
    while (!feof(in) && n > 0)
    {
        copy(buffer, n, out, &pos);
        n = fread(buffer, sizeof(unsigned char), BUFFER_LENGTH, in);
    }
    if (n > 0)
    {
        copy(buffer, n, out, &pos);
    }
    print_footer(out);
}

static void print_header(FILE *out, char *filename, char *dsname)
{
    fprintf(out, "/*\n");
    fprintf(out, "\t%s\n\n", filename);
    fprintf(out, "\tHeader file generated by File2Array. Do not edit\n");
    fprintf(out, "*/\n\n");
    fprintf(out, "#ifndef _FILE2ARRAY_\n\n#define _FILE2ARRAY_\n\n");
    fprintf(out, "static unsigned char %s[] = {", dsname);
}

static void copy(Tbuffer buffer, int n, FILE *out, int *pos)
{
    int i;

    for (i = 0; i < n; i++)
    {
        if (*pos > 0)
        {
            fprintf(out, ",");
        }
        if ((*pos) % 16 == 0)
        {
            fprintf(out, "\n/* %7d */", *pos);
        }
        fprintf(out, "%4d", buffer[i]);
        (*pos)++;
    }
}

static void print_footer(FILE *out)
{
    fprintf(out, "\n};\n\n");
    fprintf(out, "#endif\n");
}

